import time
x = 1
print("M", sep ="", end = "", flush= True)
time.sleep(x)
print("i", sep ="", end = "", flush= True)
time.sleep(x)
print("h", sep ="", end = "", flush= True)
time.sleep(x)
print("a", sep ="", end = "", flush= True)
time.sleep(x)
print("n", sep ="", end = "", flush= True)
time.sleep(x)
print("\b", sep ="", end = "", flush= True)
time.sleep(x)
print("\b", sep ="", end = "", flush= True)
time.sleep(x)
print("\b", sep ="", end = "", flush= True)
time.sleep(x)
print("\b", sep ="", end = "", flush= True)
time.sleep(x)
print("o", sep ="", end = "", flush= True)
time.sleep(x)
print("h", sep ="", end = "", flush= True)
time.sleep(x)
print("a", sep ="", end = "", flush= True)
time.sleep(x)
print("n", sep ="", end = "", flush= True)
time.sleep(x)